version: "3.8"

services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
  fraud_simulator:
    container_name: fraud_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2526:2526"
      - "8086:8086"
    command: --configfile /imposters/fraud_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
  lgtm:
    container_name: grafana
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

      