version: "3.8"

networks:
  monitoring:
    driver: bridge

services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters

  fraud_simulator:
    container_name: fraud_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2526:2526"
      - "8085:8085"
    command: --configfile /imposters/fraud_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters

  grafana:
    container_name: grafana-k6
    networks: [monitoring]
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - influxdb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  influxdb:
    image: influxdb:1.8          # K6 works best with InfluxDB v1.8
    container_name: influxdb
    networks: [monitoring]
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  grafana_data:
  influxdb_data:

      