apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: payment-gateway-api
  namespace: payment-gateway
spec:
  hosts:
    - api.your-domain.com
  gateways:
    - payment-gateway-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: payment-gateway-api.payment-gateway.svc.cluster.local
            port:
              number: 80
