apiVersion: v1
kind: Secret
metadata:
  name: payment-gateway-api-secrets
  namespace: payment-gateway
type: Opaque
stringData:
  ConnectionStrings__PaymentDb: "Server=payment-db;Database=PaymentGateway;User Id=payment_user;Password=CHANGE_ME;TrustServerCertificate=True"
  RabbitMq__HostName: "rabbitmq.payment-gateway.svc.cluster.local"
  RabbitMq__UserName: "payment_user"
  RabbitMq__Password: "CHANGE_ME"
