apiVersion: v1
kind: Secret
metadata:
  name: payment-gateway-api-secrets
  namespace: payment-gateway
type: Opaque
stringData:
  ConnectionStrings__PaymentDb: "CHANGE_ME"
  RabbitMq__HostName: "CHANGE_ME"
  RabbitMq__UserName: "CHANGE_ME"
  RabbitMq__Password: "CHANGE_ME"
